//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthyGrove.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HealthyGrove_ModelContainer : DbContext
    {
        public HealthyGrove_ModelContainer()
            : base("name=HealthyGrove_ModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Invasive> InvasiveSet { get; set; }
        public virtual DbSet<NonInvasive> NonInvasiveSet { get; set; }
        public virtual DbSet<SavedInvasive> SavedInvasiveSet { get; set; }
        public virtual DbSet<SavedNonInvasive> SavedNonInvasiveSet { get; set; }
        public virtual DbSet<Nursery> NurserySet { get; set; }
    }
}
