//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthyGrove.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invasive
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Invasive()
        {
            this.SavedInvasive = new HashSet<SavedInvasive>();
        }
    
        public int InvasiveId { get; set; }
        public string ScientificName { get; set; }
        public string CommonName { get; set; }
        public string PlantType { get; set; }
        public string WeedStatus { get; set; }
        public string VictorianStatus { get; set; }
        public string Area_of_potential_distribution_remaining { get; set; }
        public string Potential_for_invasion { get; set; }
        public string RiskRating { get; set; }
        public string Family { get; set; }
        public string VictorianBiomes { get; set; }
        public string Impact_on_natural_systems { get; set; }
        public string Native { get; set; }
        public string Rate_of_dispersal { get; set; }
        public string HeightRanges { get; set; }
        public string SpreadRanges { get; set; }
        public string FlowerColour { get; set; }
        public string LeafColour { get; set; }
        public string ClimateZones { get; set; }
        public string Abcission { get; set; }
        public string SoilType { get; set; }
        public string LightNeeds { get; set; }
        public Nullable<int> Impact_score { get; set; }
        public Nullable<int> Potential_distribution_score { get; set; }
        public Nullable<int> Residual_risk_score { get; set; }
        public Nullable<int> Invasiveness_score { get; set; }
        public Nullable<int> Rate_of_dispersal_score { get; set; }
        public Nullable<int> Urgency_score { get; set; }
        public Nullable<double> Risk_ranking_score { get; set; }
        public string Image { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SavedInvasive> SavedInvasive { get; set; }
    }
}
