//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthyGrove.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NonInvasive
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NonInvasive()
        {
            this.SavedNonInvasive = new HashSet<SavedNonInvasive>();
        }
    
        public int NonInvasiveId { get; set; }
        public string ScientificName { get; set; }
        public string CommonName { get; set; }
        public string PlantType { get; set; }
        public string Maintenance { get; set; }
        public string FlowerColour { get; set; }
        public string FoliageColour { get; set; }
        public string HeightRanges { get; set; }
        public string Native { get; set; }
        public string SpreadRanges { get; set; }
        public string ClimateZones { get; set; }
        public string WaterNeeds { get; set; }
        public string LightNeeds { get; set; }
        public string SoilType { get; set; }
        public string FrostTolerance { get; set; }
        public string Abcission { get; set; }
        public string Image { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SavedNonInvasive> SavedNonInvasive { get; set; }
    }
}
