//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthyGrove.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nursery
    {
        public int Id { get; set; }
        public string NurseryName { get; set; }
        public string Suburb { get; set; }
        public string Postcode { get; set; }
    }
}
