//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthyGrove.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SavedInvasive
    {
        public int SavedInvasiveId { get; set; }
        public string UserId { get; set; }
        public int InvasiveId { get; set; }
    
        public virtual Invasive Invasive { get; set; }
    }
}
